version: "3.8"
services:

  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=blog_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432" 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d blog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: express_app
    environment:
      - DATABASE_URL=postgresql://postgres:${DB_PASSWORD}@postgres_db:5432/blog_db?schema=public
      - PORT=3000
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
    command: >
      sh -c "
      sleep 10 &&
      npx prisma migrate dev &&
      npm run start
      "

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
